const capacidadDB = {
    "agilidad": [
        { "frase": "La agilidad es pivotar sin perder el equilibrio.", "reto": "Cambia una prioridad que no esté dando resultados hoy." },
        { "frase": "Menos burocracia, más acción.", "reto": "Resuelve un pendiente por chat en vez de agendar una reunión." },
        { "frase": "La velocidad es buena, pero la dirección es mejor.", "reto": "Define el objetivo de tu reunión en el primer minuto." },
        { "frase": "Equivócate rápido, aprende más rápido.", "reto": "Comparte un error reciente y qué aprendiste de él." },
        { "frase": "La perfección es enemiga de lo hecho.", "reto": "Lanza esa idea al 80%, no esperes al 100%." },
        { "frase": "Simplicidad es maximizar el trabajo no realizado.", "reto": "Elimina un paso innecesario en un proceso hoy." },
        { "frase": "Diciendo y haciendo: menos PPT, más prototipos.", "reto": "Muestra un ejemplo visual en lugar de explicarlo con láminas." },
        { "frase": "La agilidad requiere coraje para decir la verdad.", "reto": "Levanta la mano si crees que un proyecto no va por buen camino." },
        { "frase": "Iterar es la base de la mejora continua.", "reto": "Pide feedback de un borrador, no de un producto final." },
        { "frase": "Sé agua, adáptate al recipiente.", "reto": "Adáptate a una nueva herramienta sin quejarte hoy." },
        { "frase": "La parálisis por análisis detiene el progreso.", "reto": "Ponle fecha límite a una decisión hoy mismo." },
        { "frase": "Pequeñas victorias llevan a grandes éxitos.", "reto": "Divide un proyecto gigante en 3 tareas minúsculas para hoy." },
        { "frase": "Anticipa, no solo reacciones.", "reto": "Prepara una solución para un problema que aún no ocurre." },
        { "frase": "La agilidad es mentalidad, no solo metodología.", "reto": "Cuestiona un 'siempre se ha hecho así' hoy." },
        { "frase": "Responde al cambio sobre seguir un plan rígido.", "reto": "Ajusta tu agenda para atender algo crítico que surgió." },
        { "frase": "Optimiza el flujo, no solo la tarea individual.", "reto": "Identifica dónde se detiene el trabajo en tu equipo." },
        { "frase": "Sé un facilitador, no un bloqueador.", "reto": "Da una aprobación que tengas pendiente hace horas." },
        { "frase": "La curiosidad impulsa la rapidez.", "reto": "Investiga una forma más rápida de hacer lo de siempre." },
        { "frase": "Empieza y termina tus reuniones a tiempo.", "reto": "Finaliza tu próxima reunión 5 minutos antes de lo previsto." },
        { "frase": "Escucha al cliente, él tiene la ruta.", "reto": "Valida una idea con un usuario interno hoy." },
        { "frase": "Hazlo simple, pero significativo.", "reto": "Escribe un correo de menos de 5 líneas para un tema clave." },
        { "frase": "La agilidad es disciplina constante.", "reto": "Cumple hoy el compromiso que hiciste ayer sin excusas." },
        { "frase": "Menos correos, más conversaciones directas.", "reto": "Resuelve un malentendido con una llamada de 2 minutos." },
        { "frase": "El tiempo es nuestro recurso más escaso.", "reto": "Reduce una reunión de 60 minutos a 30 minutos." },
        { "frase": "Toma decisiones con el 70% de la información.", "reto": "No esperes a tenerlo todo para dar el primer paso." },
        { "frase": "La agilidad es un deporte de equipo.", "reto": "Ayuda a un compañero a destrabar un proceso lento." },
        { "frase": "Aprende de los errores de los demás.", "reto": "Pregunta a un colega sobre un reto que superó esta semana." },
        { "frase": "Mantén la calma en la incertidumbre.", "reto": "Respira profundo antes de responder a un cambio brusco." },
        { "frase": "Agilidad es libertad con responsabilidad.", "reto": "Hazte cargo de un problema de inicio a fin hoy." },
        { "frase": "Hoy es el mejor día para empezar.", "reto": "Ejecuta esa idea que anotaste hace una semana." }
    ],
    "colaboracion": [
        { "frase": "Juntos pa' las que sea: el apoyo mutuo es ley.", "reto": "Ofrece ayuda a alguien de otra área hoy." },
        { "frase": "Si quieres ir rápido ve solo, si quieres llegar lejos ve acompañado.", "reto": "Busca un socio para tu próximo proyecto." },
        { "frase": "El talento gana juegos, el equipo campeonatos.", "reto": "Reconoce el logro de un compañero en público." },
        { "frase": "Nadie es más inteligente que todos nosotros juntos.", "reto": "En la próxima reunión, invita a participar a quien menos habla." },
        { "frase": "La confianza es el pegamento del equipo.", "reto": "Cumple una promesa pequeña que hiciste a un colega." },
        { "frase": "Colaborar es sumar fuerzas, no dividir tareas.", "reto": "Pregunta a un compañero: '¿En qué puedo facilitarte el día?'." },
        { "frase": "El conocimiento que no se comparte se pierde.", "reto": "Enseña un truco de software o proceso a un compañero." },
        { "frase": "Escuchar es el primer paso de la colaboración.", "reto": "Escucha 5 minutos sin interrumpir en tu próxima charla." },
        { "frase": "Rompe los silos, construye puentes.", "reto": "Presenta a dos personas de diferentes áreas que deban conocerse." },
        { "frase": "La sinergia multiplica resultados.", "reto": "Haz una lluvia de ideas de 10 minutos con alguien más." },
        { "frase": "Sé el compañero que te gustaría tener.", "reto": "Sé puntual y llega preparado a la reunión de otro." },
        { "frase": "La empatía es el alma de Tigo.", "reto": "Pregúntale a un colega cómo se siente, no solo qué hace." },
        { "frase": "Construye sobre las ideas de los demás.", "reto": "En lugar de decir 'pero', di 'y además podríamos...'." },
        { "frase": "Un equipo unido es invencible.", "reto": "Propón un café virtual de 10 min para conectar con el equipo." },
        { "frase": "La generosidad es contagiosa.", "reto": "Comparte un documento o plantilla útil que tú creaste." },
        { "frase": "Pide ayuda, es un signo de fortaleza.", "reto": "Admite que no sabes algo y pide orientación hoy." },
        { "frase": "Sincroniza antes de actuar.", "reto": "Asegúrate de que tu equipo sabe en qué estás trabajando hoy." },
        { "frase": "El respeto es la base de la unión.", "reto": "Da las gracias formalmente por un favor recibido hoy." },
        { "frase": "Busca la solución, no el culpable.", "reto": "Cuando algo falle, enfócate en cómo arreglarlo en equipo." },
        { "frase": "Co-crear es mejor que imponer.", "reto": "Construye una solución usando la idea de otra persona." },
        { "frase": "Defiende el trabajo de tu equipo.", "reto": "Respalda a un colega frente a una crítica externa." },
        { "frase": "La retroalimentación es un regalo.", "reto": "Pide feedback sobre tu nivel de colaboración." },
        { "frase": "Aclara expectativas siempre.", "reto": "Pregunta: '¿Qué esperas de mí en este proceso?'." },
        { "frase": "La diversidad nos hace más fuertes.", "reto": "Busca la opinión de alguien con un perfil opuesto al tuyo." },
        { "frase": "Celebra los éxitos ajenos.", "reto": "Felicita a alguien por un logro que no tenga que ver contigo." },
        { "frase": "Resuelve conflictos hablando de frente.", "reto": "Aclara hoy ese malentendido que te tiene incómodo." },
        { "frase": "Sé un imán de soluciones.", "reto": "Llega a la reunión con una propuesta de apoyo lista." },
        { "frase": "La lealtad al equipo es clave.", "reto": "Prioriza el objetivo grupal sobre el interés individual hoy." },
        { "frase": "Colaborar requiere humildad.", "reto": "Acepta una sugerencia de un compañero con mente abierta." },
        { "frase": "Juntos somos ADN Tigo.", "reto": "Usa el 'nosotros' en lugar del 'yo' en tus correos hoy." }
    ],
    "foco": [
        { "frase": "Foco es decir NO a lo urgente para atender lo importante.", "reto": "Rechaza una reunión donde no eres esencial hoy." },
        { "frase": "Donde va tu atención, va tu energía.", "reto": "Apaga notificaciones por 2 horas para avanzar en tu prioridad #1." },
        { "frase": "Hacer mucho no es ser productivo.", "reto": "Elige tus 3 tareas 'No Negociables' del día y termínalas." },
        { "frase": "El éxito requiere un enfoque de rayo láser.", "reto": "Termina una sola tarea de principio a fin sin hacer multitasking." },
        { "frase": "La claridad precede al éxito.", "reto": "Escribe tus 3 metas de la semana en un post-it visible." },
        { "frase": "Priorizar es elegir qué batallas perder.", "reto": "Elimina hoy una tarea de tu lista que sea irrelevante." },
        { "frase": "El foco requiere silencio mental.", "reto": "Trabaja 45 minutos seguidos sin abrir el correo o chat." },
        { "frase": "Lo urgente rara vez es importante.", "reto": "Atiende tu tarea más difícil en tu hora de mayor energía." },
        { "frase": "La disciplina del foco es la verdadera libertad.", "reto": "Respeta tu bloque de tiempo para 'Trabajo Profundo' hoy." },
        { "frase": "Elimina el ruido innecesario.", "reto": "Limpia tu escritorio físico y digital de distracciones." },
        { "frase": "Mide lo que realmente importa.", "reto": "Revisa tus indicadores clave antes de empezar la jornada." },
        { "frase": "Termina lo que empiezas.", "reto": "No abras un nuevo tema hasta cerrar el que tienes pendiente." },
        { "frase": "El foco vence al talento desordenado.", "reto": "Organiza tu agenda de mañana antes de terminar hoy." },
        { "frase": "Foco es presencia total.", "reto": "No mires el celular mientras alguien te está hablando." },
        { "frase": "La intención sin foco es solo una ilusión.", "reto": "Ponle hora exacta a tu tarea más compleja del día." },
        { "frase": "Full Foco en el cliente.", "reto": "Identifica qué tarea de hoy impacta directamente al usuario." },
        { "frase": "Menos es más.", "reto": "Simplifica un reporte o presentación quitando lo que sobra." },
        { "frase": "Enfócate en la solución, no en el obstáculo.", "reto": "No hables del problema por más de 5 minutos; busca la salida." },
        { "frase": "La atención es el nuevo oro.", "reto": "Lee un documento técnico largo sin distraerte ni una vez." },
        { "frase": "Foco es consistencia diaria.", "reto": "Trabaja en tu proyecto principal a la misma hora hoy." },
        { "frase": "Evita los ladrones de tiempo.", "reto": "No entres a redes sociales hasta la hora del almuerzo." },
        { "frase": "La profundidad genera valor real.", "reto": "Estudia a fondo un tema de tu área que dominas a medias." },
        { "frase": "Enfócate en lo que puedes controlar.", "reto": "Deja de preocuparte por una decisión que no depende de ti." },
        { "frase": "Foco es resistencia a la distracción.", "reto": "Di 'espera un momento' cuando alguien intente interrumpirte." },
        { "frase": "El foco transforma esfuerzo en resultados.", "reto": "Evalúa al final del día: ¿En qué se fue tu tiempo realmente?" },
        { "frase": "Mantén el ojo en el objetivo final.", "reto": "Recuerda el propósito de tu área antes de empezar una tarea tediosa." },
        { "frase": "Full Foco es vivir el presente.", "reto": "Haz una sola cosa a la vez con toda tu intención." },
        { "frase": "La claridad mental nace del orden.", "reto": "Planifica tus primeras 2 horas de mañana desde hoy." },
        { "frase": "El foco te da paz mental.", "reto": "Saca todos tus pendientes de la cabeza y escríbelos en una lista." },
        { "frase": "Sé implacable con tus prioridades.", "reto": "No dejes que lo trivial te robe el tiempo de lo vital." }
    ],
    "integridad": [
        { "frase": "Integridad es hacer lo correcto aunque nadie te mire.", "reto": "Reporta un error propio antes de que alguien más lo note." },
        { "frase": "No todo se vale: tus valores son tu brújula.", "reto": "Si ves algo que no está bien, levanta la mano y dilo." },
        { "frase": "La transparencia genera tranquilidad.", "reto": "Comparte los datos reales hoy, aunque no sean los esperados." },
        { "frase": "Tu reputación se construye con lo que haces hoy.", "reto": "Sé puntual en todas tus citas y reuniones de este día." },
        { "frase": "La ética no es negociable en Tigo.", "reto": "Sigue el proceso correcto aunque tome un poco más de tiempo." },
        { "frase": "Sé coherente entre lo que dices y lo que haces.", "reto": "Ejecuta hoy esa tarea que ayer dijiste que era prioritaria." },
        { "frase": "Dale el crédito a quien realmente tuvo la idea.", "reto": "Menciona el aporte de un colega en tu próximo informe." },
        { "frase": "No hables de alguien que no está presente.", "reto": "Detén un chisme o comentario negativo en el equipo hoy." },
        { "frase": "Admite que no sabes en lugar de inventar.", "reto": "Responde 'no lo sé, pero lo investigo' ante una duda técnica." },
        { "frase": "Trata a todos con el mismo respeto.", "reto": "Saluda y agradece con la misma calidez a todos los niveles." },
        { "frase": "Si te equivocas, pide disculpas y repara el daño.", "reto": "Llama a alguien a quien le fallaste y busca una solución." },
        { "frase": "La integridad es valentía silenciosa.", "reto": "Mantén tu postura ética frente a una presión externa." },
        { "frase": "Cuida los recursos de la empresa como propios.", "reto": "Sé consciente del ahorro de energía o materiales hoy." },
        { "frase": "Protege la información confidencial siempre.", "reto": "Bloquea tu pantalla cada vez que te levantes de tu puesto." },
        { "frase": "No tomes atajos peligrosos.", "reto": "No te saltes un paso de seguridad por 'ahorrar tiempo'." },
        { "frase": "La verdad no necesita explicación larga.", "reto": "Sé directo y honesto en una respuesta incómoda hoy." },
        { "frase": "Tu palabra es tu contrato personal.", "reto": "Cumple hoy una promesa que hiciste la semana pasada." },
        { "frase": "La integridad construye confianza duradera.", "reto": "Sé transparente sobre un retraso antes de que te pregunten." },
        { "frase": "Sé un ejemplo para los nuevos integrantes.", "reto": "Explícale a un practicante por qué 'No todo se vale'." },
        { "frase": "La lealtad empieza por la honestidad radical.", "reto": "Dile a tu líder algo que se puede mejorar en el equipo." },
        { "frase": "No ignores lo que está mal hecho.", "reto": "Reporta una falla que todos están pasando por alto." },
        { "frase": "Sé impecable con tus palabras.", "reto": "No uses el sarcasmo para criticar el trabajo de otros." },
        { "frase": "Integridad es servicio genuino.", "reto": "Ayuda a un cliente interno sin esperar nada a cambio." },
        { "frase": "Honra tus valores personales siempre.", "reto": "Identifica tus 3 valores base y vive uno de ellos hoy." },
        { "frase": "La verdad construye puentes sólidos.", "reto": "Aclara un malentendido con un colega hoy mismo." },
        { "frase": "Sé firme con lo que es correcto.", "reto": "No cedas ante una práctica que no sea ética." },
        { "frase": "La madurez es asumir la responsabilidad.", "reto": "No busques culpables externos; busca soluciones éticas." },
        { "frase": "La ética es el alma de nuestra cultura.", "reto": "Lee una página de nuestro Código de Ética hoy." },
        { "frase": "Predica con el ejemplo siempre.", "reto": "Si pides compromiso, sé el primero en demostrarlo." },
        { "frase": "Duerme tranquilo haciendo lo correcto.", "reto": "Haz una buena acción anónima por un compañero hoy." }
    ],
    "talento": [
        { "frase": "Eres protagonista de tu propio desarrollo.", "reto": "Dedica 15 minutos hoy a aprender algo totalmente nuevo." },
        { "frase": "Tu mejor versión está por venir.", "reto": "Aprende un nuevo truco en una herramienta que usas diario." },
        { "frase": "El aprendizaje es el combustible del talento.", "reto": "Lee un artículo o mira un video de 5 min sobre tu industria." },
        { "frase": "Tú eres el dueño de tu carrera profesional.", "reto": "Agenda una sesión de feedback con un mentor hoy." },
        { "frase": "El talento es un músculo que se entrena.", "reto": "Enfréntate a una tarea que te dé un poco de miedo hoy." },
        { "frase": "Sé curioso, no solo eficiente.", "reto": "Pregunta '¿por qué se hace así?' a un proceso antiguo." },
        { "frase": "Enseña lo que sabes para reforzar tu talento.", "reto": "Guía a un compañero en un tema que tú domines bien." },
        { "frase": "Tu actitud determina tu altitud.", "reto": "Mantén una postura positiva frente a un reto difícil hoy." },
        { "frase": "Sal de tu zona de confort para crecer.", "reto": "Ofrece liderar una iniciativa pequeña esta semana." },
        { "frase": "Invierte tiempo en tu crecimiento personal.", "reto": "Busca un curso o webinar de tu interés y regístrate." },
        { "frase": "El talento Tigo busca soluciones creativas.", "reto": "Piensa en 3 formas diferentes de resolver un problema común." },
        { "frase": "Sé un eterno aprendiz.", "reto": "Aprende a usar una función nueva de Excel o software hoy." },
        { "frase": "La excelencia es un hábito, no un acto.", "reto": "Revisa tu trabajo dos veces antes de entregarlo hoy." },
        { "frase": "Define tu propósito en lo que haces.", "reto": "Escribe en una frase por qué te apasiona tu trabajo." },
        { "frase": "Escucha para crecer profesionalmente.", "reto": "Toma nota de los consejos de un líder con experiencia." },
        { "frase": "La resiliencia es una forma de talento.", "reto": "Si algo sale mal, analiza el aprendizaje y vuelve a intentar." },
        { "frase": "Sé un referente en tu tema técnico.", "reto": "Comparte un tip útil en el chat de tu equipo hoy." },
        { "frase": "El compromiso con tu mejora se nota.", "reto": "Llega con una idea fresca a tu próxima reunión de equipo." },
        { "frase": "Tu red de contactos es tu patrimonio.", "reto": "Conecta con alguien de otra ciudad en la empresa hoy." },
        { "frase": "Sé un embajador orgulloso de Tigo.", "reto": "Habla de un proyecto que te guste con un familiar hoy." },
        { "frase": "La humildad permite el aprendizaje continuo.", "reto": "Acepta una corrección técnica sin justificarte." },
        { "frase": "La innovación empieza en tu mente.", "reto": "Propón una mejora para una tarea que te parezca aburrida." },
        { "frase": "Sé imparable en la búsqueda de tus metas.", "reto": "No te rindas ante el primer obstáculo que veas hoy." },
        { "frase": "Eres el motor que mueve a la compañía.", "reto": "Haz una lista de tus 3 mayores logros de este mes." },
        { "frase": "Busca retos que te desafíen de verdad.", "reto": "Pide una responsabilidad adicional que te obligue a estudiar." },
        { "frase": "La autogestión es la clave del éxito.", "reto": "Organiza tus tareas sin esperar a que te den instrucciones." },
        { "frase": "Mantente actualizado en tendencias digitales.", "reto": "Busca qué es lo último en IA o tecnología para tu área." },
        { "frase": "El talento Tigo es diverso y único.", "reto": "Aprende algo sobre la cultura o hobbies de un compañero." },
        { "frase": "Sé un mentor para los que vienen detrás.", "reto": "Ayuda a un nuevo integrante a entender la cultura Tigo." },
        { "frase": "Valora tu propio esfuerzo diario.", "reto": "Regálate 5 minutos al final del día para celebrar tus avances." }
    ]
};
