const frasesDB = {
    "agilidad": [
        { "id": 1, "frase": "La agilidad no es correr, es pensar con claridad y actuar con decisión.", "reto": "Toma una decisión pendiente en los primeros 10 minutos de tu jornada." },
        { "id": 2, "frase": "Mejor hecho que perfecto; la perfección es el freno del progreso.", "reto": "Entrega hoy un avance 'borrador' para recibir feedback temprano." },
        { "id": 3, "frase": "La agilidad es la capacidad de adaptarse al cambio.", "reto": "Cambia el orden de tu agenda hoy para priorizar lo que realmente importa." },
        { "id": 4, "frase": "El movimiento genera información; el estancamiento genera dudas.", "reto": "Empieza esa tarea que te intimida durante solo 5 minutos seguidos." },
        { "id": 5, "frase": "Simplicidad es el arte de maximizar el trabajo no realizado.", "reto": "Identifica un paso innecesario en un proceso y propón eliminarlo." },
        { "id": 6, "frase": "Diciendo y haciendo: la brecha debe ser mínima.", "reto": "Si una tarea toma menos de 2 minutos, hazla ahora mismo." },
        { "id": 7, "frase": "Un pequeño paso hoy es mejor que un gran plan futuro.", "reto": "Termina hoy el pendiente más antiguo que tengas en tu lista." },
        { "id": 8, "frase": "La velocidad se logra eliminando obstáculos.", "reto": "Limpia tu escritorio o archivos para trabajar sin distracciones." },
        { "id": 9, "frase": "Agilidad es aprender mientras haces.", "reto": "Prueba una nueva técnica de productividad hoy mismo." },
        { "id": 10, "frase": "El éxito de hoy no garantiza el de mañana.", "reto": "Lee una noticia sobre tendencias y compártela con tu equipo." },
        { "id": 11, "frase": "La burocracia mental es el peor enemigo.", "reto": "Resuelve un tema por chat en lugar de agendar una reunión." },
        { "id": 12, "frase": "Actúa con la información que tienes hoy.", "reto": "Define el siguiente paso concreto para tu proyecto más grande." },
        { "id": 13, "frase": "La agilidad colectiva nace de la confianza.", "reto": "Valida con un compañero si tu prioridad actual es la correcta." },
        { "id": 14, "frase": "Equipos ágiles hablan más y escriben menos correos.", "reto": "Sustituye un correo extenso por una breve nota de voz." },
        { "id": 15, "frase": "El feedback es el desayuno de los campeones.", "reto": "Pide a alguien una opinión honesta sobre algo que terminaste hoy." },
        { "id": 16, "frase": "Coordinar es ganar; no trabajes en una isla.", "reto": "Pregunta a tu equipo: '¿Hay algo que me esté bloqueando?'" },
        { "id": 17, "frase": "La claridad es el motor de la rapidez.", "reto": "Explica un objetivo a un colega en menos de 30 segundos." },
        { "id": 18, "frase": "Innovar es mejorar lo existente a gran velocidad.", "reto": "Propón una mejora pequeña a una herramienta diaria." },
        { "id": 19, "frase": "El futuro pertenece a los que aprenden rápido.", "reto": "Dedica 10 minutos a aprender un atajo de teclado nuevo." },
        { "id": 20, "frase": "ADN Tigo es ser protagonistas del cambio.", "reto": "Escribe una meta de agilidad para alcanzar este viernes." }
    ],
    "colaboracion": [
        { "id": 1, "frase": "Nadie es más inteligente que todos nosotros juntos.", "reto": "Suma la opinión de alguien con un perfil distinto al tuyo hoy." },
        { "id": 2, "frase": "La colaboración trabaja hacia una visión común.", "reto": "Recuerda al equipo el objetivo principal antes de iniciar." },
        { "id": 3, "frase": "El equipo gana campeonatos.", "reto": "Ofrece tu apoyo en una tarea que no sea 'tuya'." },
        { "id": 4, "frase": "En la diversidad está nuestra mayor riqueza.", "reto": "Escucha con apertura a un compañero con el que suelas discrepar." },
        { "id": 5, "frase": "Ayudar es nuestra forma de acelerar.", "reto": "Pregunta a alguien sobrecargado: '¿Cómo te ayudo hoy?'" },
        { "id": 6, "frase": "Juansot pa' las que sea: ningún problema es ajeno.", "reto": "Resuelve un bloqueo de un compañero antes de lo tuyo." },
        { "id": 7, "frase": "La información compartida es poder multiplicado.", "reto": "Envía un resumen breve de tu última reunión a quien no asistió." },
        { "id": 8, "frase": "Un equipo comunicado es un equipo que fluye.", "reto": "Actualiza tu estado de avance en la herramienta común." },
        { "id": 9, "frase": "El éxito se celebra en plural.", "reto": "Agradece a alguien que te ayudó a destrabar algo hoy." },
        { "id": 10, "frase": "Colaborar es simplificarle la vida al otro.", "reto": "Organiza tus archivos para que cualquier compañero los entienda." },
        { "id": 11, "frase": "La empatía es el pegamento de la colaboración.", "reto": "Valida cómo se siente tu equipo antes de entrar en operación." },
        { "id": 12, "frase": "Si tú brillas, Tigo brilla.", "reto": "Resalta el aporte de un colega en un chat grupal." },
        { "id": 13, "frase": "Los silos dividen, los puentes conectan.", "reto": "Llama a un colega de otra área solo para conectar." },
        { "id": 14, "frase": "Pedir ayuda es señal de liderazgo.", "reto": "Levanta la mano hoy sobre ese tema en el que estás atascado." },
        { "id": 15, "frase": "Escuchar activamente es el primer paso.", "reto": "En tu reunión, resume lo que el otro dijo antes de responder." },
        { "id": 16, "frase": "La confianza se construye con pequeños gestos.", "reto": "Comparte un 'tip' técnico que ahorre tiempo a otros." },
        { "id": 17, "frase": "Co-crear es mejor que imponer.", "reto": "Pide ideas en lugar de dar la solución final de inmediato." },
        { "id": 18, "frase": "El futuro del trabajo es una red.", "reto": "Participa en una iniciativa que impacte a toda la compañía." },
        { "id": 19, "frase": "Dejamos huella cuando trabajamos con propósito.", "reto": "Define con un compañero una mejora para implementar este mes." },
        { "id": 20, "frase": "ADN Tigo es ser un solo equipo imparable.", "reto": "Escribe un compromiso de colaboración para este trimestre." }
    ],
    "enfoque": [
        { "id": 1, "frase": "Foco es decir NO a cien buenas ideas.", "reto": "Elimina una tarea que no aporta valor de tu lista de hoy." },
        { "id": 2, "frase": "Donde pones tu atención, pones tu energía.", "reto": "Define tu 'Roca del Día' y no pares hasta terminarla." },
        { "id": 3, "frase": "La multitarea arruina las cosas.", "reto": "Realiza una sola tarea a la vez, cerrando otras pestañas." },
        { "id": 4, "frase": "La claridad es el mejor filtro.", "reto": "Escribe tu meta semanal donde puedas verla siempre." },
        { "id": 5, "frase": "Estar ocupado no es ser productivo.", "reto": "Al final del día, tacha lo que realmente generó impacto." },
        { "id": 6, "frase": "Proteger tu tiempo sagrado.", "reto": "Bloquea 1 hora para 'trabajo profundo' sin interrupciones." },
        { "id": 7, "frase": "El silencio es la herramienta del enfoque.", "reto": "Pon tu celular en modo 'No molestar' en tareas críticas." },
        { "id": 8, "frase": "Pequeños avances constantes vencen a grandes esfuerzos.", "reto": "Dedica 15 minutos sin parar a ese reporte difícil." },
        { "id": 9, "frase": "Bandeja vacía es mente despejada.", "reto": "Responde correos que tomen menos de 2 minutos." },
        { "id": 10, "frase": "La disciplina de empezar es la mitad del éxito.", "reto": "Inicia tu jornada con la tarea que más pereza te dé." },
        { "id": 11, "frase": "Notificaciones son distracciones disfrazadas.", "reto": "Desactiva alertas de correo mientras redactas documentos." },
        { "id": 12, "frase": "Termina lo que empiezas.", "reto": "No abras una nueva tarea hasta cerrar la anterior." },
        { "id": 13, "frase": "Reuniones cortas, acuerdos claros.", "reto": "Pide la agenda antes de entrar a una reunión." },
        { "id": 14, "frase": "Respeta los espacios de otros.", "reto": "No envíes mensajes fuera de horario laboral." },
        { "id": 15, "frase": "Comunicar el foco evita distracciones.", "reto": "Inicia diciendo: 'Mi objetivo hoy con este tema es...'" },
        { "id": 16, "frase": "Respetar el tiempo ajeno es integridad.", "reto": "Llega 2 minutos antes a tu próxima reunión." },
        { "id": 17, "frase": "Alinearse es ahorrar energía.", "reto": "Pregunta a tu líder qué genera más impacto hoy." },
        { "id": 18, "frase": "La visión requiere enfoque diario.", "reto": "Haz algo hoy que te acerque a donde quieres estar en un año." },
        { "id": 19, "frase": "Simplificar el futuro es la meta.", "reto": "Propón reducir la complejidad de un reporte mensual." },
        { "id": 20, "frase": "ADN Tigo es ser precisos como un láser.", "reto": "Escribe tres objetivos de alto impacto para el próximo mes." }
    ],
    "integridad": [
        { "id": 1, "frase": "Integridad es hacer lo correcto siempre.", "reto": "Revisa un proceso a medias y termínalo con excelencia." },
        { "id": 2, "frase": "Nuestra reputación se construye con verdades.", "reto": "Si no sabes algo, dilo honestamente y busca la solución." },
        { "id": 3, "frase": "No todo se vale para un resultado.", "reto": "Evalúa si tu camino de hoy respeta nuestros valores." },
        { "id": 4, "frase": "Coherencia es decir y hacer lo mismo.", "reto": "Cumple hoy ese compromiso verbal que hiciste." },
        { "id": 5, "frase": "La ética es el cimiento.", "reto": "Lee un punto del Código de Ética y compártelo." },
        { "id": 6, "frase": "La honestidad radical nos fortalece.", "reto": "Si detectas un error, corrígelo e infórmalo." },
        { "id": 7, "frase": "Respetar la diversidad es integridad.", "reto": "Asegúrate de que todos hablen en tu reunión." },
        { "id": 8, "frase": "La puntualidad es respeto.", "reto": "Termina tus reuniones 5 minutos antes." },
        { "id": 9, "frase": "Cuidar los recursos es tarea de todos.", "reto": "Optimiza el uso de una herramienta para evitar desperdicio." },
        { "id": 10, "frase": "La verdad nos permite mejorar.", "reto": "Da un feedback sincero a alguien que lo necesite." },
        { "id": 11, "frase": "Protegemos la información.", "reto": "Bloquea tu pantalla cada vez que te levantes." },
        { "id": 12, "frase": "Ser responsable de nuestras acciones.", "reto": "Si algo salió mal, asume tu parte y propón el arreglo." },
        { "id": 13, "frase": "La transparencia construye.", "reto": "Si alguien habla mal de otro, resalta una cualidad." },
        { "id": 14, "frase": "Damos crédito a quien lo merece.", "reto": "Menciona al compañero que te dio la idea hoy." },
        { "id": 15, "frase": "La inclusión no es negociable.", "reto": "Incluye a alguien callado en una decisión hoy." },
        { "id": 16, "frase": "Trata como quieres ser tratado.", "reto": "Responde correos con tono amable y profesional." },
        { "id": 17, "frase": "Confianza basada en transparencia.", "reto": "Informa de un retraso antes de que venza el plazo." },
        { "id": 18, "frase": "Construimos un legado de honestidad.", "reto": "Escribe un ejemplo de ética que viste hoy." },
        { "id": 19, "frase": "Tigo depende de nuestra credibilidad.", "reto": "Asegúrate de que tus reportes reflejen la realidad." },
        { "id": 20, "frase": "ADN Tigo es ser luz en cada acción.", "reto": "Define un valor personal que sea tu sello." }
    ],
    "talento": [
        { "id": 1, "frase": "Tu talento es tu regalo a la compañía.", "reto": "Usa tu mayor fortaleza para resolver un problema complejo." },
        { "id": 2, "frase": "Aprendizaje continuo es la moneda del futuro.", "reto": "Lee 10 minutos sobre una tendencia de Tigo." },
        { "id": 3, "frase": "Sé el dueño de tu mapa de aprendizaje.", "reto": "Agenda tu primera hora de estudio en la plataforma." },
        { "id": 4, "frase": "Tu curiosidad es el motor.", "reto": "Haz una pregunta profunda para entender mejor el negocio." },
        { "id": 5, "frase": "El talento crece en los desafíos.", "reto": "Acepta esa tarea fuera de tu zona de confort." },
        { "id": 6, "frase": "Pasar de la queja a la propuesta.", "reto": "Presenta un problema junto con dos soluciones." },
        { "id": 7, "frase": "Nunca dejes de ser estudiante.", "reto": "Aprende un atajo de Excel o sistema hoy." },
        { "id": 8, "frase": "Feedback es combustible.", "reto": "Pide: '¿Qué debería hacer para ser mejor?'" },
        { "id": 9, "frase": "Tu marca se construye con resultados.", "reto": "Dale un toque extra de calidad a tu entregable hoy." },
        { "id": 10, "frase": "El bienestar potencia el talento.", "reto": "Tómate 5 minutos de pausa activa hoy." },
        { "id": 11, "frase": "Somos lo que hacemos repetidamente.", "reto": "Establece un hábito saludable para tu mañana." },
        { "id": 12, "frase": "Tu actitud multiplica tus aptitudes.", "reto": "Afronta el reto más difícil con mente positiva." },
        { "id": 13, "frase": "Enseñar es aprender dos veces.", "reto": "Explícale un proceso difícil a un compañero." },
        { "id": 14, "frase": "El reconocimiento es motor del talento.", "reto": "Envía un elogio por el trabajo de otro equipo." },
        { "id": 15, "frase": "Busca mentores, sé un mentor.", "reto": "Pide 15 minutos de charla a alguien que admires." },
        { "id": 16, "frase": "Tu red es tu patrimonio profesional.", "reto": "Preséntate con alguien nuevo hoy." },
        { "id": 17, "frase": "Liderazgo es influencia.", "reto": "Guía a tu equipo hacia una solución constructiva." },
        { "id": 18, "frase": "Tigo es el lugar de tus sueños.", "reto": "Escribe tres metas para tus próximos dos años." },
        { "id": 19, "frase": "Prepararse hoy para el cargo de mañana.", "reto": "Identifica qué habilidad te falta y búscala." },
        { "id": 20, "frase": "ADN Tigo es evolucionar sin límites.", "reto": "Propón una idea que cambie cómo trabajamos hoy." }
    ]
};
